import Navbar from '@/components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <link rel="stylesheet" href="https://bootswatch.com/5/sketchy/bootstrap.min.css" />
      </head>
      <body>
        <Navbar />
        <div className='container p-4'>{children}</div>
      </body>
    </html>
  );
}
